name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # runs pipeline when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run build/test
      - name: Run build
        run: npm start &

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "dummy-app" ]; then
              git clone https://github.com/MinahilNisar/dummy-app-ci-cd.git dummy-app
            else
              cd dummy-app && git pull origin main
            fi
            cd dummy-app
            npm install
            nohup npm start > app.log 2>&1 &
